alert("Contador de Votos para Presidente");
let nome1 = prompt("Qual o nome do primeiro candidato?: ");
let nome2 = prompt("Qual o nome do segundo candidato?: ");
let nome3 = prompt("Qual o nome do terceiro candidato?: ");
let votos1 = parseInt(prompt("Quantos votos o (a) " + nome1 + " ganhou?: "));
let votos2 = parseInt(prompt("Quantos votos o (a) " + nome2 + " ganhou?: "));
let votos3 = parseInt(prompt("Quantos votos o (a) " + nome3 + " ganhou?: "));
let votosNulos = parseInt(prompt("Quantos votos foram nulos?: "));
let votosBrancos = parseInt(prompt("Quantos votos foram brancos?: "));
let totalHabitantes = votos1 + votos2 + votos3 + votosNulos + votosBrancos;
let votosValidos = votos1 + votos2 + votos3;
let percentualVotosValidos = (votosValidos / totalHabitantes) * 100;
let percentualNome1 = (votos1 / totalHabitantes) * 100;
let percentualNome2 = (votos2 / totalHabitantes) * 100;
let percentualNome3 = (votos3 / totalHabitantes) * 100;
let percentualVotosNulos = (votosNulos / totalHabitantes) * 100;
let percentualVotosBrancos = (votosBrancos / totalHabitantes) * 100;
alert("Temos " + totalHabitantes + " habitantes");
alert("Temos " + percentualVotosValidos.toFixed(2) + "% de votos válidos ou " + votosValidos);
alert("Temos " + percentualNome1.toFixed(2) + "% de votos válidos ou " + votos1 + " para o (a) " + nome1);
alert("Temos " + percentualNome2.toFixed(2) + "% de votos válidos ou " + votos2 + " para o (a) " + nome2);
alert("Temos " + percentualNome3.toFixed(2) + "% de votos válidos ou " + votos3 + " para o (a) " + nome3);
alert("Temos " + percentualVotosNulos.toFixed(2) + "% de votos nulos ou " + votosNulos);
alert("Temos " + percentualVotosBrancos.toFixed(2) + "% de votos brancos ou " + votosBrancos);